# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tolday I learned
email: deathbullet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I write code. Which is fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://darshanime.github.io" # the base hostname & protocol for your site
twitter_username: deathbullet
github_username:  darshanime

# Build settings
markdown: kramdown
